### ISSUE TITLE
Hot reload

### ISSUE THREAD

**Issue by scorpnode** [kataras/iris#192]
For faster development, hot reload by watching changes to files and when files are saved iris recompiles
like
iris run file.go
##

**Comment by kataras** [comment]
Excellent idea, start coding that on a while!

**Comment by p4tin** [comment]
+1

**Comment by kataras** [comment]
@scorpnode  Done, I need you to test it on linux :) Thanks you!!

**Comment by kataras** [comment]
@scorpnode  Done, I need you to test it on linux :) Thanks you!!

- https://github.com/kataras/iris/tree/master/iris#run

**Comment by tonylinyy** [comment]
I update to rc2 on mac,but auto re-run does not work
if you need I can help to test

**Comment by kataras** [comment]
@tonylinyy Yes I need testers for linux and osx, thanks you!! I will notify you later to test again

**Comment by kataras** [comment]
@tonylinyy  I installed a linux myself and a borrowed a macosx, but thanks you!

Tested and working now.

[![Iris CLI run showcase](https://raw.githubusercontent.com/iris-contrib/website/gh-pages/assets/iris_command_line_tool_run_command.png)](https://raw.githubusercontent.com/iris-contrib/website/gh-pages/assets/iris_command_line_tool_run_command.png)

[![Iris CLI run showcase linux](https://raw.githubusercontent.com/iris-contrib/website/gh-pages/assets/iris_command_line_tool_run_linux.png)](https://raw.githubusercontent.com/iris-contrib/website/gh-pages/assets/iris_command_line_tool_run_linux.png)

**Comment by p4tin** [comment]
Just tested on max osx and it did not reload, I tried changing the go file no reload and I also tried templates no change....   Is there a way to recompile templates each call so that changes show right away?

➜  enigma iris version
3.0.0-rc.2%

**Comment by kataras** [comment]
@p4tin 

>  Is there a way to recompile templates each call so that changes show right away?

Yes, just do: ` iris.Config.Render.Template.IsDevelopment = true ` 

> Just tested on max osx and it did not reload, I tried changing the go file no reload

what's your iris command line tool's version? (type ` iris help` on your shell )

**Comment by p4tin** [comment]
➜  gocodecloud git:(master) ✗ iris help
NAME:
   iris - Command line tool for Iris web framework

USAGE:
   iris command [arguments...]

VERSION:
   0.0.6

**Comment by kataras** [comment]
I will look it later, I don't know why didn't worked on you yet

**Comment by p4tin** [comment]
Some info about my Mac...

![image](https://cloud.githubusercontent.com/assets/7197804/16216768/81d874e0-373b-11e6-9a4e-1cb57ea2bab6.png)

**Comment by cgyy** [comment]
@kataras  I think it should watch the hole source folder, not just the main.go

**Comment by kataras** [comment]
@cgyy ` utils.WatchDirectoryChanges(workingDir, func(fname string) {` it does watching the hole source folder alread, why you said that? :)

**Comment by cgyy** [comment]
@kataras 
I do like this:
```shell
cd ~/gowork/src/hello_iris/backend
iris run main.go
```

and I see, when other *.go file changed, iris does not reload

**Comment by xpbliss** [comment]
maybe the ```iris run ``` should learn from the goal https://github.com/colegion/goal

**Comment by qskousen** [comment]
@kataras I'm having the same issue as @cgyy - when I do `iris run myprogram.go` it reloads if I edit `myprogram.go` but not when I edit any other files in subdirectories that are imported in `myprogram.go`, like custom middleware or routes.

**Comment by kataras** [comment]
@cgyy  @qskousen Fixed now, don't miss the [HISTORY.md](https://github.com/kataras/iris/tree/master/HISTORY.md) for other changes too! Thanks

**Comment by cgyy** [comment]
@kataras  There is a new problem, after file reload, the log can not print to terminal

**Comment by kataras** [comment]
Yes the log is disabled because of if you have print banner enabled  then the banner will be print out on every reload, if you're ok with this I will change this behavior

**Comment by cgyy** [comment]
@kataras  I understand, thank you!

**Comment by kataras** [comment]
@cgyy  I just changed this behavior, you don't need to do anything, after the first time the banner will not be print out. I added a flag inside iris, and set that flag from the iris command line tool

**Comment by cgyy** [comment]
@kataras I see, great work!

**Comment by kataras** [comment]
Thanks!!

**Comment by p4tin** [comment]
On my mac I am still not seeing reload...  I just did a go get -u github.com/kataras/iris and go get -u  github.com/kataras/iris/iris  (on rc3 now)

**Comment by kataras** [comment]
@p4tin I know, the fix wasn't for macos... I am waiting for mac os x access from an iris user to find out what's going on

**Comment by p4tin** [comment]
codegansta - has a reload the gin project (https://github.com/codegangsta/gin -- main.go) that works on all OSes..  He used the standard go library...  The pertinent code is:
```
func scanChanges(watchPath string, cb scanCallback) {
	for {
		filepath.Walk(watchPath, func(path string, info os.FileInfo, err error) error {
			if path == ".git" {
				return filepath.SkipDir
			}

			// ignore hidden files
			if filepath.Base(path)[0] == '.' {
				return nil
			}

			if filepath.Ext(path) == ".go" && info.ModTime().After(startTime) {
				cb(path)
				startTime = time.Now()
				return errors.New("done")
			}

			return nil
		})
		time.Sleep(500 * time.Millisecond)
	}
}
```

**Comment by kataras** [comment]
Yes I could do that... for ever loop, but currently the Iris receives events from the OS when a file change happens, it doesn't walk the folder forever..

**Comment by p4tin** [comment]
On my Mac fsnotify seems to be doing something weird (note my go file is called 'fswatcher.go':

If I open the file in "atom" and watch the directory, on a save, I get this as output from the fsnotifications:
```
2016/06/24 19:36:53 event: "fswatcher.go": CHMOD
2016/06/24 19:36:53 event: "fswatcher.go": WRITE
2016/06/24 19:36:53 modified file: "fswatcher.go": WRITE fswatcher.go
2016/06/24 19:36:55 event: "fswatcher.go": CHMOD
```

If I open it in atom and also have it open in Webstorm, I make a change from atom, I see this:
```
2016/06/24 19:37:12 event: "fswatcher.go": CHMOD
2016/06/24 19:37:12 event: "fswatcher.go": WRITE
2016/06/24 19:37:12 modified file: "fswatcher.go": WRITE fswatcher.go
2016/06/24 19:37:13 event: "fswatcher.go": CHMOD
2016/06/24 19:37:13 event: "fswatcher.go": WRITE
2016/06/24 19:37:13 modified file: "fswatcher.go": WRITE fswatcher.go
2016/06/24 19:37:14 event: "fswatcher.go": CHMOD
```

and only open in WebStorm:
```
2016/06/24 19:36:05 event: "fswatcher.go___jb_tmp___": CREATE
2016/06/24 19:36:05 event: "fswatcher.go___jb_old___": CREATE
2016/06/24 19:36:05 event: "fswatcher.go": RENAME
2016/06/24 19:36:05 renamed file: "fswatcher.go": RENAME fswatcher.go
2016/06/24 19:36:05 event: "fswatcher.go": CREATE
2016/06/24 19:36:05 event: "fswatcher.go___jb_tmp___": RENAME|CHMOD
2016/06/24 19:36:05 renamed file: "fswatcher.go___jb_tmp___": RENAME|CHMOD fswatcher.go___jb_tmp___
2016/06/24 19:36:05 event: "fswatcher.go": CHMOD
2016/06/24 19:36:06 event: "fswatcher.go": CHMOD
```

I hope this helps

**Comment by kataras** [comment]
The hot-reload feature moved to its own project named `rizla` you can find it on my repositories, now it should be working, I made it even better, notify on new folders, watch new folders when added, remove all if events, it accepts any change and much more, tested on linux,macos and windows

**Comment by lijunfeng** [comment]
update laster version,don't hot-reload in window,why?

**Comment by kataras** [comment]
@lijunfeng I just tested it for windows, again, and is, I changed a subfolder's .go file and it reloads, only '.go'  files are watched, if you want reload for templates you should use the  ` iris.Config.Render.Template.IsDevelopment = true`

**Comment by lijunfeng** [comment]
thanks

**Comment by lijunfeng** [comment]
My operating system is window 10,According to your Solution  Still not success.
I output log, only monitor to main.go file.

**Comment by kataras** [comment]
The default matcher and watcher watches the `.go` files ignore the `vendor` and `node_modules` for any case, I tested on win7, ubuntu 16.04 and macos windows 10 has trouble with that? I will install a virtual machine and talk to you again

**Comment by foliot** [comment]
Check out CompileDemon: https://github.com/githubnemo/CompileDaemon. Its simple and gets the job done on my Mac.

**Comment by kataras** [comment]
@foliot 'Nice' implementation, https://github.com/githubnemo/CompileDaemon/blob/master/daemon.go#L370
