### ISSUE TITLE
context.Param(...) on routes without named params

### ISSUE THREAD

**Issue by pbberlin** [kataras/iris#351]
context.Param works fine,
unless it is called for a context without a named param.

iris.Get("/paramgroup/:paramgroup_name",handler01)
iris.Get("/another-route",handler02)

handler01(c){
    p := c.Param("paramgroup_name")   // works wonderfully
}

handler02(c){
    p := c.Param("paramgroup_name")   // yields irritating results
}

**Comment by allen13** [comment]
So the current behavior (I just tested this and reviewed the code) is to return an empty string when no parameters match. You could handle any issues by doing:
    
    if param_value == "" {
    }

What specifically do you mean when you say "irritating results"?

**Comment by pbberlin** [comment]
But I receive param_values such as "ttt" or "css".
They have the length of the last previous valid value.
But the content is random trash.

This occurs sometimes, not always.
As if the goroutines maintain a state.

Regards
  Peter

**Comment by allen13** [comment]
That's odd. Sounds like some kind of caching going on. Looking at the Param code I see no way that this could happen. However something could be going on at another level. I just tried to replicate this in my own environment, but can seem to reproduce this. Is it possible for you to provide more information about your environment? Code, platform, requests, etc...?

**Comment by kataras** [comment]
@pbberlin Params are reseting on each request, this is impossible to be an Iris issue, please provide more information in order to help you, I will close this issue because the report is invalid, ok?

**Comment by pbberlin** [comment]
I put some tracing code into the iris source and ferret out the reason.

I get back to you.

Thanks
  Peter

**Comment by kataras** [comment]
Upgrade your iris package first, please:

1. Remove your $GOPATH/src/github.com/kataras/iris ( in order to have a 'clean install')
2. Open shell and execute: ` go get -u github.com/kataras/iris/iris` 

Try again, and if the issue still to be an issue, share the code and the the exact flow you follow in order to be able to re-produce this issue to my machine to debug it please, thanks you, I will wait!

**Comment by kataras** [comment]
@pbberlin Peter, when you're here please respose to me, I need to tell you what code to change in order to test it

**Comment by pbberlin** [comment]
Dear kataras,

I made a clean install.

I put some debugging messages into the iris code.

Result: 
The garbled values come from the **session**.

At the end of on

1. e request, last line of iris handler code, session key x has value "cit".
2. At the beginning of next request, same session key has value "ttt". Same length, but different characters.

I will create a piece of code to reproduce the issue (or find my own bumbling),
and get back to you.

Kind regards
 Peter

I

**Comment by pbberlin** [comment]
Dear Kataras,

I created a [repository](https://github.com/pbberlin/iris_session) to demonstrate.

Just clone it and run  

`go run main.go paramsintoession.go`

Open http://localhost:8088/ in browser and click

"Test session persistennce" several times.

On my Windows 64bit system, I receive "eeoup1" instead of group1.

Also - and amazingly - I receive the value "cit" - 
which is from another go server running on a different port.

Regards
  Peter

**Comment by kataras** [comment]
@pbberlin I just wake up, I will drink a cup of coffee and I look to it immediately, no need to open a new issue (yet(?)) , 

> Also - and amazingly - I receive the value "cit" -
which is from another go server running on a different port.

from another go server running on a different port?  iris insances are not sharing anything between each other, this is very strange, we will see it later

**Comment by kataras** [comment]
OK.

Path Parameters are working fine, so the title is not correct, sessions are working too but you have some code which is strange and gives these results you told about, for example:


here you are setting the sessions values each time, sessions are meant to be kept no need to make something like this
```go
		for key, defaultVal := range keysToPersist {
			if reqVal, ok := EffectiveParamIsSet(c, key); ok {
				c.Session().Set(key, reqVal)
				continue
			}
			// setting default values
			if sessVal := c.Session().GetString(key); sessVal == "" {
				c.Session().Set(key, defaultVal)
			}
		}

		// Dump currently persisted params
		for key, _ := range keysToPersist {
			log.Printf("sess key %17v is %-11v - %s", key, c.Session().GetString(key), p)
		}
```

the routes:
```go
	i01.Get("/paramgroup", index)
	i01.Get("/paramgroup/:paramgroup_name", index)
	i01.Get("/second-route", secondRoute)
```

When I pressed the link it navigates me to /paramgroup so it doesn't has a parameter, so it gives the session's paramgroup_name's value which is `cit`. If you changed that to /paramgroup/group1 it gives you the paramgroup_name = `group` because it gets it from path parameters as the `EffectiveParamIsSet` does (checks the path parameters before session's ), so it gives the results we are waiting for, if you navigate back to /paramgroup_name it gives you, correctly, the `cit` so it doesn't caches the result from path parameters or something like that, path parameters are correctly reseting on each request.

/second-route gives you the flash message as we expecting to do, so flashes are ok here.

The problem with `eeoup1` (which is really strange) has been given because of wrong use of sessions at this code block:

```go

	// log.Printf("log-point5: %#v", c.Session().GetAll())
	/*
		for key, defaultVal := range keysToPersist {
			if reqVal, ok := EffectiveParamIsSet(c, key); ok {
				c.Session().Set(key, reqVal)
				continue
			}
			// setting default values
			if sessVal := c.Session().GetString(key); sessVal == "" {
				c.Session().Set(key, defaultVal)
			}
		}

		// Dump currently persisted params
		for key, _ := range keysToPersist {
			log.Printf("sess key %17v is %-11v - %s", key, c.Session().GetString(key), p)
		}
	*/

```
If you chnaged that on something like that:

```go

	once.Do(func() {
		log.Printf("Setting sessions values")
		for k, v := range keysToPersist {
			c.Session().Set(k, v)
		}
		for key := range keysToPersist {
			log.Printf("sess key %17v is %-11v - %s", key, c.Session().GetString(key), p)
		}
	})

```
then all works just fine, so we will focus on the 'wrong' code block

**Comment by kataras** [comment]
OK.

Path Parameters are working fine, so the title is not correct, sessions are working too but you have some code which is strange and gives these results you told about, for example:


here you are setting the sessions values each time, sessions are meant to be kept no need to make something like this on each request inside a middleware
```go
		for key, defaultVal := range keysToPersist {
			if reqVal, ok := EffectiveParamIsSet(c, key); ok {
				c.Session().Set(key, reqVal)
				continue
			}
			// setting default values
			if sessVal := c.Session().GetString(key); sessVal == "" {
				c.Session().Set(key, defaultVal)
			}
		}

		// Dump currently persisted params
		for key, _ := range keysToPersist {
			log.Printf("sess key %17v is %-11v - %s", key, c.Session().GetString(key), p)
		}
```

the routes:
```go
	i01.Get("/paramgroup", index)
	i01.Get("/paramgroup/:paramgroup_name", index)
	i01.Get("/second-route", secondRoute)
```

When I pressed the link it navigates me to /paramgroup so it doesn't has a parameter, so it gives the session's paramgroup_name's value which is `cit`. If you changed that to /paramgroup/group1 it gives you the paramgroup_name = `group` because it gets it from path parameters as the `EffectiveParamIsSet` does (checks the path parameters before session's ), so it gives the results we are waiting for, if you navigate back to /paramgroup_name it gives you, correctly, the `cit` so it doesn't caches the result from path parameters or something like that, path parameters are correctly reseting on each request.

/second-route gives you the flash message as we expecting to do, so flashes are ok here.

The problem with `eeoup1` (which is really strange) has been given because of wrong use of sessions at this code block:

```go

	// log.Printf("log-point5: %#v", c.Session().GetAll())
	/*
		for key, defaultVal := range keysToPersist {
			if reqVal, ok := EffectiveParamIsSet(c, key); ok {
				c.Session().Set(key, reqVal)
				continue
			}
			// setting default values
			if sessVal := c.Session().GetString(key); sessVal == "" {
				c.Session().Set(key, defaultVal)
			}
		}

		// Dump currently persisted params
		for key, _ := range keysToPersist {
			log.Printf("sess key %17v is %-11v - %s", key, c.Session().GetString(key), p)
		}
	*/

```
If you chnaged that on something like that:

```go

	once.Do(func() {
		log.Printf("Setting sessions values")
		for k, v := range keysToPersist {
			c.Session().Set(k, v)
		}
		for key := range keysToPersist {
			log.Printf("sess key %17v is %-11v - %s", key, c.Session().GetString(key), p)
		}
	})

```
then all works just fine, so we will focus on the 'wrong' code block

**Comment by kataras** [comment]
OK.

Path Parameters are working fine, so the title is not correct, sessions are working too(90%) but you have some code which is strange and gives these results you told about, for example:


here you are setting the sessions values each time, sessions are meant to be kept no need to make something like this on each request inside a middleware ( the problem is here) 
```go
		for key, defaultVal := range keysToPersist {
			if reqVal, ok := EffectiveParamIsSet(c, key); ok {
				c.Session().Set(key, reqVal)
				continue
			}
			// setting default values
			if sessVal := c.Session().GetString(key); sessVal == "" {
				c.Session().Set(key, defaultVal)
			}
		}

		// Dump currently persisted params
		for key, _ := range keysToPersist {
			log.Printf("sess key %17v is %-11v - %s", key, c.Session().GetString(key), p)
		}
```

navigate to /paramgroup_name gives `eeoup1`, if we navigate to /paramgroup_name/group1 and back to /paramgroup_name it gives the correct, `group1` so something is setting to the sessions the wrong value, the path,urlparameters  are not setting the `eeoup1`,

if we change this code to something like this, then all works just fine:

```go

	once.Do(func() {
		log.Printf("Setting sessions values")
		for k, v := range keysToPersist {
			c.Session().Set(k, v)
		}
		for key := range keysToPersist {
			log.Printf("sess key %17v is %-11v - %s", key, c.Session().GetString(key), p)
		}
	})

```


the routes:
```go
	i01.Get("/paramgroup", index)
	i01.Get("/paramgroup/:paramgroup_name", index)
	i01.Get("/second-route", secondRoute)
```

When I pressed the link it navigates me to /paramgroup so it doesn't has a parameter, so it gives the session's paramgroup_name's value which is `cit`. If you changed that to /paramgroup/group1 it gives you the paramgroup_name = `group1` because it gets it from path parameters as the `EffectiveParamIsSet` does (checks the path parameters before session's ), so it gives the results we are waiting for, if you navigate back to /paramgroup_name it gives you, correctly, the `cit` so it doesn't caches the result from path parameters or something like that, path parameters are correctly reseting on each request.

/second-route gives you the flash message as we expecting to do, so flashes are ok here.

The problem with `eeoup1` (which is really strange) has been given because of wrong use of sessions at this code block:

```go

	// log.Printf("log-point5: %#v", c.Session().GetAll())
	/*
		for key, defaultVal := range keysToPersist {
			if reqVal, ok := EffectiveParamIsSet(c, key); ok {  // here and 
				c.Session().Set(key, reqVal) // here is the issue 
				continue
			}
			// setting default values
			if sessVal := c.Session().GetString(key); sessVal == "" {
				c.Session().Set(key, defaultVal)
			}
		}

		// Dump currently persisted params
		for key, _ := range keysToPersist {
			log.Printf("sess key %17v is %-11v - %s", key, c.Session().GetString(key), p)
		}
	*/

```

so we will focus on the code block which setting sessions on each request depends on the EffectiveParameter

**Comment by pbberlin** [comment]
Dear Kataras,

As first thing: Sorry for "cit".
This was of course an artefact from the orginal code.
The value should have been initialized with "group1".

Second:
I integrated your init suggestion: 
Session init is only done **once**, via once.

Third:
You have a point to object to "update session with session".
There was a redundant session.Set... in the design.
I fixed this, by separating Effective**Request**Param from
Effective**(Overall)**Param.

Session should only be updated when there is a new **request** param.

I pushed all your changes - and mine into the repo.

`git pull`
`go run main.go`

Now and with go 1.7 - "group1" is still changing to "eeoup1".

Can you point me to the reason again?

Kind regards
  Peter

**Comment by kataras** [comment]
I'm trying to solve this among all other things I'm doing (ssh remote control for iris), I will response back when it has been solved, thanks all these again

**Comment by pbberlin** [comment]
Dear Kataras,

First: Take your time.

Secondly, some observations:

Session works fine until c.Redirect().
After c.Redirect(), session is garbled.

Session change is **not** caused by a session.Set().
It just changes between requests, after a c.Redirect().

Is there maybe an internal mechanic, 
which gets confused during redirection?


Kind regards
  Peter

**Comment by kataras** [comment]
No, I tested it, I kept the c.Redirect but removed the c.SetFlash and it was worked on me, it printed the correct results, and the opossite, I removed the c.Redirect and keep c.SetFlash, and make the redirect manually and the issue remains, so I suppose that the issue is not c.Redirect(which was the first thing I though too) but the c.SetFlash

**Comment by kataras** [comment]
**FIXED**!!  , it was fasthttp bug I replaced this:

```go
	cKey := flashMessageCookiePrefix + key
	cValue := base64.URLEncoding.EncodeToString([]byte(value))
		c := fasthttp.AcquireCookie()
		c.SetKey(cKey)
		c.SetValue(cValue)
		c.SetPath("/")
		c.SetHTTPOnly(true)
		ctx.RequestCtx.Request.Header.SetCookie(cKey, cValue)
		ctx.RequestCtx.Response.Header.SetCookie(c)
		fasthttp.ReleaseCookie(c)
```

with:

```go
	ctx.RequestCtx.Request.Header.SetCookie(cKey, cValue)
	ctx.RequestCtx.Response.Header.Add("Set-Cookie", cKey+"="+cValue+"; Path:/; HttpOnly")
```

**Comment by kataras** [comment]
@pbberlin It was a silly fix as you saw, please verify it and tell me if that works on you too, upgrade with `go get -u github.com/kataras/iris` , thanks for your time and your pattience!!

**Comment by kataras** [comment]
@pbberlin It was a silly fix as you saw, please verify it and tell me if that works on you too, upgrade with `go get -u github.com/kataras/iris` , thanks for your time and your pattience!!

> I changed the title to be more specific

**Comment by pbberlin** [comment]
Dear Kataras,

I repeated 
`get -u github.com/kataras/iris`
two times.

Sadly no change in behavior.

Kind regards
  Peter

**Comment by kataras** [comment]
That's bad news... let me try to backup my code and download again the repository to re-produce the issue

**Comment by kataras** [comment]
I will make a pr to your repo in order to see the difference with the 'working' version, I can't see with my eyes any semantic difference except the names (which I changed them when the issue was still issue on me, so I assume this is not the issue, but I will try with the original names again)

**Comment by kataras** [comment]
OK, found the difference, see [this repo](https://github.com/q-contrib/iris_session), it was the `/second-route` if we change it to `/redirect` or something else, then it's working (lol(?))

**Comment by kataras** [comment]
That's very strange the `-` character should be allowed as route path, at least we know what's excactly is wrong now, I'll fix it and response you back

**Comment by kataras** [comment]
Dear @pbberlin,

I think we waste time, it was not Iris or fasthttp issue at all, if you made a copy of your `keysToPersist` to a new map then the values are clear (because never setted to sessions, with the current code) I made them set once and it's working, the issue was that we're re-using the map, it shows awful from the beginning but I hope that you did it only to demonstrate the 'bug', but this was the bug xD

**Comment by pbberlin** [comment]
Dear Kataras,

I doubt this solution.

- Maps are safe for concurrent _reads_

- `go build -race ` shows no signs of data races either.

- After the first request, the `store` map is now always empty . Therefore, the bug went away.

- As soon as `store` is filled again, the bug re-occurs.
Even though I put the map iteration into a mutex block of code.

> ... removed the c.SetFlash and...

I removed all c.GetFlash and c.SetFlash calls, and replaced them with session logic. 
The bug still occurs.

Kind regards
  Peter

**Comment by pbberlin** [comment]
Dear Kataras,

I removed path parameters and fell back to Url Get parameters.
The problem went away.

So the issue is priority B now.

Regards
  Peter

**Comment by kataras** [comment]
Dear Peter,

Try to replace the `/second-route` with `/secondroute` and the problem will go away also, or otherwise replace the `paramgroup` path with `param-group`.

About the previous comment, the sessions is filled and store is filled also, you have right for maps are safe for read-only concurrently but I though that if session doesn't change itself so it's the map reflecting the values, the code is working if we just copy the map to a temporary request-scope store on the first request (where sync.Do plays in the example code).

I found many solutions yesterday, some of them has to do with paths as you told already, no need to remove the path parameters. Just don't use paths with dashes(`-`) replace all `/simple-path/` with `/simple/path` users don't like/trust coblex url, with dashes and other 'symbols'.

About the main source of the problem, I think that is problem of the example, I can't thing a way which I could ever use that code in real project ( read-set cycle and initialization of sessions with global variable), so we are ok for now, you have right it's not a first priority anymore, at least we know how to fix it, thanks for all again!

Regards,
Makis

**Comment by kataras** [comment]
Dear Peter,

Try to replace the `/second-route` with `/secondroute` and the problem will go away also, or otherwise replace the `paramgroup` path with `param-group`.

About the previous comment, the sessions is filled and store is filled also, you have right for maps are safe for read-only concurrently but I though that if session doesn't change itself so it's the map reflecting the values, the code is working if we just copy the map to a temporary request-scope store on the first request (where sync.Do plays in the example code).

I found many solutions yesterday, some of them has to do with paths as you told already, no need to remove the path parameters. Just don't use paths with dashes(`-`) replace all `/simple-path/` with `/simple/path` users don't like/trust coblex url, with dashes and other 'symbols'.

About the main source of the problem, I think that is problem of the example, I can't thing a way which I could ever use that code in real project ( read-set cycle and initialization of sessions with global variable), so we are ok for now, you have right it's not a first priority anymore, at least we know how to apply a user-specific-fix it, thanks for all again!

Regards,
Makis

**Comment by pbberlin** [comment]
Dear Makis,

I eliminated all hyphens from routes and param names.
And the problem persists.

If you say, that my application logic serves is no 
legitimate or reasonable purpose,
then I would politely disagree.

In any case, I want to discontinue this conversation now.

Regards
  Peter

**Comment by kataras** [comment]
As you whish sir
