### ISSUE TITLE
Error when running go get -u

### ISSUE THREAD

**Issue by DisgruntledBadger** [kataras/iris#521]
- Version : **V4-LTS**

- Operating System: 4.8.4-1-ARCH

When I run the command at the top of README.md to install:

go get -u github.com/kataras/iris/iris

I get the following error:

# github.com/kataras/iris
go/src/github.com/kataras/iris/websocket.go:92: cannot use s.Server.HandleConnection (type func("github.com/kataras/go-websocket".UnderlineConnection)) as type func("gopkg.in/kataras/go-websocket.v0".UnderlineConnection) in argument to "github.com/iris-contrib/websocket".Custom

Any idea why this might be ?

**Comment by kataras** [comment]
Hello, can you try to re-produce this again?

**Comment by DisgruntledBadger** [comment]
Reproduce how ? I can run go get -u ... again and it always give me the same error.

The stable version is working but I've installed the github version on another machine with the exact same OS/Version of go/GOPATH settings and it worked just fine

**Comment by kataras** [comment]
But I run `go get -u github.com/kataras/iris/iris` on a clean machine and is working, please try again now..

**Comment by DisgruntledBadger** [comment]
Ok, I made it to work by removing iris-contrib and running the command again. I'm unsure why it worked, but I guess it has to do with the package manager...

**Comment by kataras** [comment]
No, each of the repository iris depends has its own `gopkg.in` import path for the stable v4, in order to work forever, and the current stays as it's , we had only a problem with iris-contrib/websocket which I fixed when I saw your post here :)

**Comment by kataras** [comment]
## Thanks!

**Comment by DisgruntledBadger** [comment]
oh, ok. Quick fix that was :P 
Thank you,
And also thank you for iris, I've been using it for my servers lately and this shit fucking rocks. Runs smoothly and its superbly easy to use and well documented.

**Comment by kataras** [comment]
Yeah, I try to fix things fast, I'm all time in pc when I am not sleeping so... you will have instant help anytime you ask!

Thanks for your nice words, I'm not a native english speaker, if you find something strange on docs you can make a PR to fix it: https://github.com/iris-contrib/gitbook

**Comment by tsingakbar** [comment]
`go get -u gopkg.in/kataras/iris.v5`

> # gopkg.in/kataras/iris.v5
> ../../../gopkg.in/kataras/iris.v5/websocket.go:92: cannot use s.Server.HandleConnection (type func(*http.Request, "github.com/kataras/go-websocket".UnderlineConnection)) as type func("github.com/kataras/go-websocket".UnderlineConnection) in argument to "github.com/iris-contrib/websocket".Custom

It's still not fixed.
